const config = {
  address: "0x127a2975c4E1c75f1ed4757a861bbd42523DB035",
  abi: [
    "function KP3R (  ) external view returns ( address )",
    "function acceptGovernance (  ) external",
    "function add ( address tokenA, address tokenB ) external",
    "function consult ( address tokenIn, uint256 amountIn, address tokenOut ) external view returns ( uint256 amountOut )",
    "function factory (  ) external view returns ( address )",
    "function governance (  ) external view returns ( address )",
    "function granularity (  ) external view returns ( uint8 )",
    "function lastUpdated ( address ) external view returns ( uint256 )",
    "function observationIndexOf ( uint256 timestamp ) external view returns ( uint8 index )",
    "function pairObservations ( address, uint256 ) external view returns ( uint256 timestamp, uint256 price0Cumulative, uint256 price1Cumulative )",
    "function pairs (  ) external view returns ( address[] )",
    "function pendingGovernance (  ) external view returns ( address )",
    "function periodSize (  ) external view returns ( uint256 )",
    "function setGovernance ( address _governance ) external",
    "function setKeep3r ( address _keep3r ) external",
    "function update ( address tokenA, address tokenB ) external returns ( bool )",
    "function updateFor ( uint256 i, uint256 length ) external returns ( bool updated )",
    "function updatePair ( address pair ) external returns ( bool )",
    "function updateable (  ) external view returns ( bool )",
    "function updateableFor ( uint256 i, uint256 length ) external view returns ( bool )",
    "function updateableList (  ) external view returns ( address[] list )",
    "function windowSize (  ) external view returns ( uint256 )",
    "function work (  ) external",
  ],
};
module.exports = config;
