const config = {
  address: "0x89d278c57cDef0c1cA588B95191d7759AC797A0c",
  abi: [
    "function KP3R (  ) external view returns ( address )",
    "function acceptGovernance (  ) external",
    "function add ( address tokenA, address tokenB ) external",
    "function current ( address tokenIn, uint256 amountIn, address tokenOut ) external view returns ( uint256 amountOut )",
    "function factory (  ) external view returns ( address )",
    "function governance (  ) external view returns ( address )",
    "function lastObservation ( address ) external view returns ( uint256 timestamp, uint256 price0Cumulative, uint256 price1Cumulative, uint256 timeElapsed )",
    "function lastUpdated ( address ) external view returns ( uint256 )",
    "function pairObservations ( address, uint256 ) external view returns ( uint256 timestamp, uint256 price0Cumulative, uint256 price1Cumulative, uint256 timeElapsed )",
    "function pairs (  ) external view returns ( address[] )",
    "function pendingGovernance (  ) external view returns ( address )",
    "function periodSize (  ) external view returns ( uint256 )",
    "function quote ( address tokenIn, uint256 amountIn, address tokenOut, uint256 granularity ) external view returns ( uint256 amountOut )",
    "function setGovernance ( address _governance ) external",
    "function update ( address tokenA, address tokenB ) external returns ( bool )",
    "function updateFor ( uint256 i, uint256 length ) external returns ( bool updated )",
    "function updatePair ( address pair ) external returns ( bool )",
    "function work (  ) external",
    "function workable (  ) external view returns ( bool )",
    "function workable ( address pair ) external view returns ( bool )",
  ],
};
module.exports = config;
